# See: https://github.com/bbatsov/rubocop If you want to know what is RuboCop.

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'pbr/shapes.rb'

Layout:
  Enabled: false

Style:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  
Metrics/ClassLength:
  Max: 150